version: "3.8"
services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./uploads:/app/uploads
      - ./frontend/build/static:/app/build/static

  backend:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./frontend/build/static:/app/frontend/build/static
